// Levels available in the viewer. Entity data lives in entities/<dir>.ini
// (generated by nicku-extract); mesh/collision JSON in collision/<dir>.json.
export const LEVELS = [
  ["dannyphantomlevel1", "Danny Phantom 1"],
  ["dannyphantomlevel2", "Danny Phantom 2"],
  ["dannyphantomlevel3", "Danny Phantom 3"],
  ["dannyphantomlevel4", "Danny Phantom 4"],
  ["JimmyNeutronLab", "Jimmy Neutron Lab"],
  ["JimmyNeutronLevel1_01", "Jimmy Neutron 1"],
  ["JimmyNeutronLevel4", "Jimmy Neutron 4"],
  ["SpongeBobLevel1", "SpongeBob 1"],
  ["SpongeBobLevel2", "SpongeBob 2"],
  ["SpongeBobLevel3", "SpongeBob 3"],
  ["SpongeBobLevel4", "SpongeBob 4"],
  ["TestWorld", "Test World"],
  ["TimmyTurnerLevel1", "Timmy Turner 1"],
  ["TimmyTurnerLevel2", "Timmy Turner 2"],
  ["TimmyTurnerLevel4", "Timmy Turner 4"],
].map(([dir, label]) => ({ dir, label }));
